kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: todo-ss
  namespace: project
spec:
  serviceName: todo-headless
  replicas: 1
  selector:
    matchLabels:
      app: todo-sql
  template:
    metadata:
      labels:
        app: todo-sql
    spec:
      containers:
        - name: todo-sql
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "tododb"
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - mountPath: data/
              name: sql-storage
  volumeClaimTemplates:
    - metadata:
        name: sql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service 
metadata:
  name: todo-headless
  namespace: project
spec:
  clusterIP: None
  selector:
    app: todo-sql
  ports:
    - port: 5432
      name: web



      