apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pong-svc
spec:
  type: ClusterIP
  selector:
    app: pong-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-app-svc
spec:
  type: ClusterIP
  selector:
    app: log-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000

---

apiVersion: v1
kind: Service 
metadata:
  name: pong-headless
  namespace: exercises
spec:
  clusterIP: None
  selector:
    app: pong-sql
  ports:
    - port: 5432
      name: web
