apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: log-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: pong-svc
            port:
              number: 2345
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-app-svc
            port:
              number: 2345
      - path: /pings
        pathType: Prefix
        backend:
          service:
            name: pong-svc
            port:
              number: 2345
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: pong-svc
            port:
              number: 2345
