apiVersion: v1
kind: Service
metadata:
  name: log-app-svc
spec:
  type: ClusterIP
  selector:
    app: log-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000



# apiVersion: v1
# kind: Service
# metadata:
#   name: todo
# spec:
#   type: NodePort
#   selector:
#     app: todo # This is the app as declared in the deployment.
#   ports:
#     - name: http
#       nodePort: 30080 # k3d: --port 8082:30080@agent:0 -p 8081:80@loadbalancer. This is the port that is available outside. Value for nodePort can be between 30000-32767
#       protocol: TCP
#       port: 1234 # This is a port that is available to the cluster, in this case it can be ~ anything
#       targetPort: 3000 # This is the target port


# k3d cluster create --port 8082:30080@agent:0 -p 8081:80@loadbalancer --agents 2